apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: bragger
  labels:
    app: bragger
    component: redis
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bragger
      component: redis
  template:
    metadata:
      labels:
        app: bragger
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: bragger
  labels:
    app: bragger
    component: redis
    environment: development
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: bragger
    component: redis