apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: bragger
  labels:
    app: bragger
    component: backend
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001
    protocol: TCP
    name: http
  selector:
    app: bragger
    component: backend