apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bragger
  labels:
    app: bragger
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bragger
      component: frontend
  template:
    metadata:
      labels:
        app: bragger
        component: frontend
    spec:
      containers:
      - name: frontend
        image: bragger-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      restartPolicy: Always