apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: bragger
  labels:
    app: bragger
    component: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP
    name: http
  selector:
    app: bragger
    component: frontend