apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-pvc.yaml
  - uploads-pvc.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

commonLabels:
  app: bragger
  version: v1

namespace: bragger