apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: bragger
  labels:
    app: bragger
    component: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: bragger
    component: database